# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sh-fwk/prebuilts/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sh-fwk/prebuilts

PRODUCT_COPY_FILES += \
    vendor/sh-fwk/prebuilts/proprietary/product/etc/permissions/jp.co.sharp.android.emopar.library.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/jp.co.sharp.android.emopar.library.xml \
    vendor/sh-fwk/prebuilts/proprietary/product/etc/permissions/jp.co.sharp.android.emopar.systemservice.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/jp.co.sharp.android.emopar.systemservice.xml \
    vendor/sh-fwk/prebuilts/proprietary/system_ext/etc/permissions/privapp-permissions-system-ext-m94.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-system-ext-m94.xml

PRODUCT_PACKAGES += \
    EmoParInternalContent \
    EmoParInternalContent2 \
    EmopaOverlayService \
    EmoPar \
    EmopaSystemService \
    jp.co.sharp.android.emopar.library \
    jp.co.sharp.android.emopar.systemservice
